# Generated by Django 3.2.8 on 2021-12-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simple_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sku', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Short_Decs', models.CharField(max_length=50)),
                ('Long_Desc', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Image', models.ImageField(upload_to='app/Images')),
            ],
        ),
        migrations.CreateModel(
            name='Variety_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sku', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Short_Decs', models.CharField(max_length=50)),
                ('Long_Desc', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
