# Generated by Django 3.2.8 on 2021-12-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_product',
            name='Image',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
        migrations.AlterField(
            model_name='simple_product',
            name='Long_Desc',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='simple_product',
            name='Short_Decs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variety_product',
            name='Long_Desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variety_product',
            name='Short_Decs',
            field=models.CharField(max_length=255),
        ),
    ]
