# Generated by Django 3.2.8 on 2021-12-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_product',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
